### ISSUE TITLE
Characters are upgrades

### ISSUE THREAD

**Issue by harisker** [BSData/black-seas#5]
**Describe the bug**
Based on the faq
https://www.facebook.com/groups/WarlordGamesBlackSeasandBlackPowder/permalink/512132112781041
UPGRADES & POINTS at Q2
A special character is to be considered as upgrade.
So a frigate for example that is a Medium ships can take only 2 upgrades. But now in the current data version you can select 2 upgrades and a Character which is wrong and no validation error is triggered.

**Comment by JustHerby** [comment]
I had not seen this, and still haven't as I don't have access to the facebook group! Is there a non-facebook link to this please? I've requested access but I don't know how often this group is checked.

**Comment by JustHerby** [comment]
OK, I now have access to the fb group, and I'm not 100% certain your reading of the rule is correct... Simply because the limits on p74 seem to refer specifically to the upgrades in that list, and if special characters are to count as upgrades in all ways, not just for the points cost, that means Famous Ships can't have Special Characters, which seems odd to me as then you can't have Nelson on the Victory.

The FAQ does, however, clarify that fleets can only have 1 special character and 1 famous ship, total (which makes Epic Battles on p86 of Hold Fast! make more sense, so I will add those at somepoint), so I'll leave this open with the following issues for now:

Change veterancy points to calculate after special characters are added
Limit famous ships and special characters to one per fleet

**Comment by harisker** [comment]
Hello,

In page 76 of the main rule book it says that "famous ships cannot be given any upgrades". So you cannot put Nelson on Victory but you still follow the national special rules.
Also in the same page says that "You may only pick one of EACH special characters and famous ships from your nationality". So i cannot take Nelson twice or/and add two Victory. In the example it specifies that you should choose from your own nation only.
